name       : xorg-driver-input-synaptics
version    : 1.9.1
release    : 28
source     :
    - https://www.x.org/releases/individual/driver/xf86-input-synaptics-1.9.1.tar.gz : c0b43eeacf866af2c876d253a9c9aa4df97242e5c673bf365fec261183c727ea
license    : MIT
component  : xorg.driver
summary    : Support for touchpads
description: |
    The Xorg Synaptics Driver package contains the X.Org Input Driver, support programs and SDK for Synaptics touchpads. Even though the evdev driver can handle touchpads very well, this driver is required if you want to use advanced features like multi tapping, scrolling with touchpad, turning the touchpad off while typing, etc.
optimize   :
    - no-bind-now
    - no-symbolic
builddeps  :
    - pkgconfig(libevdev)
    - pkgconfig(mtdev)
    - pkgconfig(pciaccess)
    - pkgconfig(xorg-server)
    - pkgconfig(xi)
    - pkgconfig(xproto)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    mv $installdir/usr/share/X11/xorg.conf.d/70-synaptics.conf $installdir/usr/share/X11/xorg.conf.d/50-synaptics.conf
