name       : xorg-driver-input-synaptics
version    : 1.8.99.1
release    : 13
source     :
    - https://www.x.org/releases/individual/driver/xf86-input-synaptics-1.8.99.1.tar.gz : b51188ed87b5d427417368fd6e9d5f04c81fc9c699f67f5233b94051cc4d8c8b
license    :
    - MIT
summary    : Support for touchpads
component  : xorg.driver
builddeps  :
    - pkgconfig(mtdev)
    - pkgconfig(xorg-server)
    - pkgconfig(xi)
    - pkgconfig(libevdev)
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
optimize   : no-bind-now
description: |
    The Xorg Synaptics Driver package contains the X.Org Input Driver, support programs and SDK for Synaptics touchpads. Even though the evdev driver can handle touchpads very well, this driver is required if you want to use advanced features like multi tapping, scrolling with touchpad, turning the touchpad off while typing, etc.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
