name        : xorg-driver-input-synaptics
version     : 1.8.3
release     : 12
source     :
    - http://xorg.freedesktop.org/releases/individual/driver/xf86-input-synaptics-1.8.3.tar.bz2 : d39f100c74f3673778b53f17bab7690161925e25dd998a15dd8cc69b52e83f01
license     :
    - MIT
summary     : Support for touchpads
component   : xorg.driver
builddeps   :
    - pkgconfig(mtdev)
    - pkgconfig(xorg-server)
    - pkgconfig(xi)
    - pkgconfig(libevdev)
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
optimize    : no-bind-now
description : |
    The Xorg Synaptics Driver package contains the X.Org Input Driver, support programs and SDK for Synaptics touchpads. Even though the evdev driver can handle touchpads very well, this driver is required if you want to use advanced features like multi tapping, scrolling with touchpad, turning the touchpad off while typing, etc.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
